# Generated by Django 5.0.1 on 2024-02-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('Gh', 'Ghee'), ('CZ', 'Cheese'), ('IC', 'Ice-Creams'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
