# Generated by Django 5.0.1 on 2024-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.TextField(null=True)),
                ('slider_dec', models.TextField(null=True)),
                ('slider_picture', models.ImageField(default='', upload_to='static/images/banner_2/')),
            ],
        ),
    ]
