# Generated by Django 5.0.1 on 2024-03-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_ordet_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='rozerpay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='rozerpay_payment_status',
            new_name='razorpay_payment_status',
        ),
    ]
