# Generated by Django 5.0.1 on 2024-03-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_razorpay_ordet_id_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
