# Generated by Django 5.0.1 on 2024-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_payment_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cust_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
