# Generated by Django 5.0.1 on 2024-03-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_payment_cust_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cust_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
