# Generated by Django 5.0.1 on 2024-03-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_payment_cust_id_customer_cust_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_id',
        ),
    ]
