# Generated by Django 5.0.1 on 2024-03-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_customer_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
