# Generated by Django 5.0.1 on 2024-03-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_payment_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cid',
        ),
    ]
